#!/usr/bin/env zsh

hdmi_active=$(xrandr |grep ' connected' |grep 'HDMI' |awk '{print $1}')

if [[ ! -z "$hdmi_active" ]]; then
    xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal
fi
