#!/usr/bin/env zsh 
 
if [[ $# -eq 1 ]]; then 
    selected=$1 
else 
    selected=$(tmuxinator l -n | tail -n +2 | fzf) 
fi 
 
# Exit if no directory is selected 
if [[ -z $selected ]]; then 
    exit 0 
fi 

tmuxinator start $selected
